name: GitHub Actions CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17', '1.16' ]
    name: Go ${{ matrix.go }} CI test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go version

      - name: acceptance tests
        env: 
          HPEGL_IAM_SERVICE_URL: ${{ secrets.HPEGL_IAM_SERVICE_URL }} 
          HPEGL_TENANT_ID: ${{ secrets.HPEGL_TENANT_ID }}
          HPEGL_USER_SECRET: ${{ secrets.HPEGL_USER_SECRET }}
          HPEGL_USER_ID: ${{ secrets.HPEGL_USER_ID }}
          HPEGL_VMAAS_LOCATION: ${{ secrets.HPEGL_VMAAS_LOCATION }}
          HPEGL_VMAAS_SPACE_NAME: ${{ secrets.HPEGL_VMAAS_SPACE_NAME }}
          HPEGL_API_VENDED_SERVICE_CLIENT: true
        run: make acceptance
      - run: make lint
      - run: make build
      - run: make test
